GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/663bee0b27109993fda3e318
###
DELETE http://localhost:3001/api/persons/663beef7a126bca9933fbe69
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "juas",
"number": "123-488888"
}

###
PUT http://localhost:3001/api/persons/663c8f5aae3a26be268a7559
Content-Type: application/json

{

"number": "123456"
}