GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/5
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Zhang San",
"number": "55-55-555555"
}